language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t TEST -f Dockerfile.dev ./frontend

script:
  - docker run -e CI=true USERNAME/docker-react npm run test
    
